---
- name: Validate lifecycle action
  ansible.builtin.assert:
    that:
      - lifecycle_action in ['upgrade_server', 'upgrade_agent', 'uninstall',
                              'remove_node', 'etcd_backup',
                              'rotate_certs', 'rotate_certs_agent']
    fail_msg: "Invalid lifecycle_action: {{ lifecycle_action }}"

- name: Run lifecycle action
  ansible.builtin.include_tasks: "{{ lifecycle_action }}.yml"
