---
preflight_required_kernel_modules:
  - br_netfilter
  - overlay
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack

preflight_sysctl_params:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
  fs.inotify.max_user_watches: 524288
  fs.inotify.max_user_instances: 512
  fs.file-max: 1024000
  vm.overcommit_memory: 1
  vm.panic_on_oom: 0

# System resource limits
preflight_nofile_limit: 1024000
preflight_nproc_limit: 1024000

# Logrotate
preflight_logrotate_maxsize: "250M"
