---
keepalived_vrrp_interface: "eth0"
keepalived_auth_pass: "CHANGEME"       # REQUIRED: change before deploying, max 8 chars
haproxy_stats_password: "CHANGEME!"    # REQUIRED: change before deploying
