---
all:
  children:
    loadbalancers:
      hosts:
        lb01:
          ansible_host: 192.168.1.5
        lb02:
          ansible_host: 192.168.1.6
    masters:
      hosts:
        master01:
          ansible_host: 192.168.1.10
          rke2_bootstrap: true
        master02:
          ansible_host: 192.168.1.11
        master03:
          ansible_host: 192.168.1.12
    workers:
      hosts:
        worker01:
          ansible_host: 192.168.1.20
        worker02:
          ansible_host: 192.168.1.21
        worker03:
          ansible_host: 192.168.1.22
