---
- name: Check if RKE2 is already installed
  ansible.builtin.stat:
    path: "{{ rke2_cli }}"
  register: rke2_binary

- name: Download RKE2 install script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: "{{ rke2_install_script }}"
    mode: '0700'
  when: not rke2_binary.stat.exists

- name: Install RKE2 server
  ansible.builtin.command:
    cmd: "{{ rke2_install_script }}"
    creates: "{{ rke2_cli }}"
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
    INSTALL_RKE2_TYPE: "server"
    INSTALL_RKE2_CHANNEL: "{{ rke2_channel }}"
