---
galaxy_info:
  author: bestcloudforme
  description: "kube-vip or external load balancer setup for HA control planes"
  license: Apache-2.0
  min_ansible_version: "2.19"
  platforms:
    - name: EL
      versions: ["all"]
    - name: Ubuntu
      versions: ["all"]
    - name: Debian
      versions: ["all"]
  galaxy_tags: [rke2, kubernetes, rancher]
dependencies:
  - role: rke2_common
