---
all:
  children:
    loadbalancers:
      hosts: {}
    masters:
      hosts:
        master01:
          ansible_host: 192.168.1.10
          rke2_bootstrap: true
    workers:
      hosts:
        worker01:
          ansible_host: 192.168.1.11
        worker02:
          ansible_host: 192.168.1.12
        worker03:
          ansible_host: 192.168.1.13
